server:
    port: 80

spring:
    application:
        name: mall
    datasource:
        druid:
            dev:
                name: dev
                url: jdbc:mysql://127.0.0.1:3306/mall?serverTimezone=Asia/Shanghai
                driver-class-name: com.mysql.cj.jdbc.Driver
                username: root
                password: 123456
                initial-size: 10
                max-active: 50

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true

logging:
    dev:
        config: classpath:/log4j2-dev.xml